obj-$(CONFIG_DIRECT_CHARGER) += direct_charger.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_sc.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_lvc.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charger_check.o
