#
# Copyright (c) 2021-2021 Honor Technologies Co., Ltd. All Rights Reserved.
# Description: hi556 customsized driver,
#    otp read function is samed as it's kernel driver.
# Create: 2021-01-29
#

obj-y += hi556_m190_kob.o