ifeq ($(TARGET_VERSION_MODE),factory)
ccflags-y += -DFACTORY_CHARGE_MODE
endif
obj-y      += huawei_battery.o
obj-y      += huawei_charger.o
obj-y      += huawei_fuelguage.o
obj-y      += honor_pmic_ocp_debug.o
obj-y      += charge_dmd_monitor.o
