obj-$(CONFIG_HUAWEI_TOUCH_SCREEN)   += touchscreen/
obj-$(CONFIG_PROC_IO_INFO)          += ioinfo/
obj-$(CONFIG_HONOR_POWER) += power/
obj-$(CONFIG_HONOR_USB)   += usb/
obj-$(CONFIG_CARD_TRAY_GPIO_DETECT) += card_tray/
obj-y += hihonor_oem_glink/
