#
# huawei power common drivers
#

obj-y += cc_common_module/
obj-y += cc_protocol/
obj-y += cc_coul/
obj-y += cc_hardware_ic/
obj-y += cc_hardware_monitor/
obj-y += cc_hardware_channel/
obj-y += cc_wireless/
obj-y += cc_battery/
obj-y += cc_charger/
