#ifndef __PLATFORM_MEMORY_DEF_H__
#define __PLATFORM_MEMORY_DEF_H__ 
#include <global_ddr_map.h>
#if defined(CONFIG_GCOV_ATF) || defined(CONFIG_HISI_GCOV_FASTBOOT)
#define HISI_BL31_BASE ATF_RESERVED_BL31_PHYMEM_BASE
#define HISI_BL31_RAM_ADDR HISI_BL31_BASE
#define HISI_BL31_RAM_SIZE (0x200000)
#else
#define HISI_BL31_BASE HISI_RESERVED_BL31_DATA_BASE
#define HISI_BL31_RAM_ADDR HISI_BL31_BASE
#define HISI_BL31_RAM_SIZE (0xE0000)
#endif
#define HISI_BL31_LOG_USER_ADDR (HISI_RESERVED_BL31_DATA_BASE + 0xE0000)
#define HISI_BL31_LOG_USER_SIZE (0x20000)
#define HISI_BL31_DATA_START (HISI_BL31_LOG_USER_ADDR + HISI_BL31_LOG_USER_SIZE)
#define ATF_BL31_PARAMS_FROM_FASTBOOT_PARAMS_ADDR HISI_BL31_DATA_START
#define HISI_BL31_PARAMS_FROM_FASTBOOT_PARAMS_SIZE (0x110)
#define HISI_BL31_RPMB_KEY_INFO_ADDR (ATF_BL31_PARAMS_FROM_FASTBOOT_PARAMS_ADDR + \
                HISI_BL31_PARAMS_FROM_FASTBOOT_PARAMS_SIZE)
#define HISI_BL31_RPMB_KEY_INFO_SIZE (0x20)
#define HISI_BL31_RPMB_CRYPTOGRAPHIC_KEY_ADDR (HISI_BL31_RPMB_KEY_INFO_ADDR + \
                HISI_BL31_RPMB_KEY_INFO_SIZE)
#define HISI_BL31_RPMB_CRYPTOGRAPHIC_KEY_SIZE (0x80)
#define HISI_BL31_HUK_CODE_ADDR (HISI_BL31_RPMB_CRYPTOGRAPHIC_KEY_ADDR + HISI_BL31_RPMB_CRYPTOGRAPHIC_KEY_SIZE)
#define HISI_BL31_HUK_CODE_SIZE (0x20)
#define HISI_BL31_RPMB_KEY_ADDR (HISI_BL31_HUK_CODE_ADDR + HISI_BL31_HUK_CODE_SIZE)
#define HISI_BL31_RPMB_KEY_SIZE (0x80)
#define HISI_BL31_DDRC_INFO_ADDR (HISI_BL31_RPMB_KEY_ADDR + HISI_BL31_RPMB_KEY_SIZE)
#define HISI_BL31_DDRC_INFO_SIZE (0x200)
#define NPU_PM_PARA_BASE (HISI_BL31_DDRC_INFO_ADDR + HISI_BL31_DDRC_INFO_SIZE)
#define NPU_PM_PARA_SIZE (0x100)
#define HISI_BL31_UFS_KEY_ADDR (NPU_PM_PARA_BASE + NPU_PM_PARA_SIZE)
#define HISI_BL31_UFS_KEY_SIZE (0x700)
#define HISI_BL31_RPMB_DEVICE_INFO_ADDR (HISI_BL31_UFS_KEY_ADDR + HISI_BL31_UFS_KEY_SIZE)
#define HISI_BL31_RPMB_DEVICE_INFO_SIZE (0x28)
#define HISI_BL31_RPMB_BOOT_INFO_ADDR (HISI_BL31_RPMB_DEVICE_INFO_ADDR + HISI_BL31_RPMB_DEVICE_INFO_SIZE)
#define HISI_BL31_RPMB_BOOT_INFO_SIZE (0x20)
#define BL31_FASTBOOT_HITEST_MNTN_ADDR (HISI_BL31_RPMB_BOOT_INFO_ADDR + HISI_BL31_RPMB_BOOT_INFO_SIZE)
#define BL31_FASTBOOT_HITEST_MNTN_SIZE (0x20)
#ifdef CONFIG_PRODUCT_ARMPC
#define ATF_BL31_KASLR_RESERVE_MEM_ADDR (BL31_FASTBOOT_HITEST_MNTN_ADDR + BL31_FASTBOOT_HITEST_MNTN_SIZE)
#define ATF_BL31_KASLR_RESERVE_MEM_SIZE (0xC)
#define HISI_BL31_SECDBG_SHMEM_ADDR (ATF_BL31_KASLR_RESERVE_MEM_ADDR + ATF_BL31_KASLR_RESERVE_MEM_SIZE)
#define HISI_BL31_SECDBG_SHMEM_SIZE (0x24)
#define HISI_BL31_RESERVE_MEM_ADDR (HISI_BL31_SECDBG_SHMEM_ADDR + HISI_BL31_SECDBG_SHMEM_SIZE)
#define HISI_BL31_RESERVE_MEM_SIZE (0x318)
#else
#define HISI_BL31_LB_LITE_FLAG_ADDR (BL31_FASTBOOT_HITEST_MNTN_ADDR + BL31_FASTBOOT_HITEST_MNTN_SIZE)
#define HISI_BL31_LB_LITE_FLAG_SIZE (0x2)
#define HISI_BL31_SOCID_SHMEM_ADDR (HISI_BL31_LB_LITE_FLAG_ADDR + HISI_BL31_LB_LITE_FLAG_SIZE)
#define HISI_BL31_SOCID_SHMEM_SIZE (0x20)
#define HISI_BL31_RESERVE_MEM_ADDR (HISI_BL31_SOCID_SHMEM_ADDR + HISI_BL31_SOCID_SHMEM_SIZE)
#define HISI_BL31_RESERVE_MEM_SIZE (0x326)
#endif
#define HISI_ATF_TEE_SHMEM_ADDR (HISI_BL31_RESERVE_MEM_ADDR + HISI_BL31_RESERVE_MEM_SIZE)
#define HISI_ATF_TEE_SHMEM_SIZE (0x1000)
#define HISI_BL31_HISEE_ADDR (HISI_ATF_TEE_SHMEM_ADDR + HISI_ATF_TEE_SHMEM_SIZE)
#define HISI_BL31_HISEE_SIZE (0x4FE000)
#ifdef CONFIG_PRODUCT_ARMPC
#define HISI_BL2_BL31_HIBERNATE_ADDR (HISI_BL31_HISEE_ADDR + HISI_BL31_HISEE_SIZE)
#define HISI_BL2_BL31_HIBERNATE_SIZE (0x1000)
#define HISI_BL31_HIBERNATE_ADDR (HISI_BL2_BL31_HIBERNATE_ADDR + HISI_BL2_BL31_HIBERNATE_SIZE)
#define HISI_BL31_HIBERNATE_SIZE (0x40000)
#define HISI_HIBERNATE_TEEOS_KEYS_ADDR (HISI_BL31_HIBERNATE_ADDR + HISI_BL31_HIBERNATE_SIZE)
#define HISI_HIBERNATE_TEEOS_KEYS_SIZE (0x400)
#define HISI_BL31_SIZE (ATF_RESERVED_BL31_PHYMEM_SIZE - HISI_BL31_HISEE_SIZE - \
                        HISI_BL2_BL31_HIBERNATE_SIZE - HISI_BL31_HIBERNATE_SIZE - \
                        HISI_HIBERNATE_TEEOS_KEYS_SIZE)
#else
#define HISI_BL31_SIZE (ATF_RESERVED_BL31_PHYMEM_SIZE - HISI_BL31_HISEE_SIZE)
#endif
#define ATF_BL31_LOG_ADDR HISI_BL31_NS_LOG_BASE
#define ATF_BL31_LOG_SIZE HISI_BL31_NS_LOG_SIZE
#define ATF_BL2_RAM_BASE (ATF_RESERVED_BL2_PHYMEM_BASE)
#define ATF_BL2_RAM_SIZE (ATF_RESERVED_BL2_PHYMEM_SIZE)
#define HISI_BL2_RAM_END (ATF_BL2_RAM_BASE + ATF_BL2_RAM_SIZE)
#define ATF_BL2_LOG_SIZE (HISI_SUB_RESERVED_BL2_LOG_MEM_PHYMEM_SIZE)
#define ATF_BL2_LOG_ADDR (HISI_SUB_RESERVED_BL2_LOG_MEM_PHYMEM_BASE)
#define ATF_BL2_SHMEM_SIZE 0x10000
#define ATF_BL2_SHMEM_ADDR (HISI_BL2_RAM_END - ATF_BL2_SHMEM_SIZE)
#define HISI_BL2_CC_DATA_SIZE 0x100000
#define HISI_BL2_CC_DATA_ADDR (ATF_BL2_SHMEM_ADDR - HISI_BL2_CC_DATA_SIZE)
#define HISI_BL2_DDR_SHMEM_SIZE 0xD000
#define HISI_BL2_DDR_SHMEM_ADDR (HISI_BL2_CC_DATA_ADDR - HISI_BL2_DDR_SHMEM_SIZE)
#define HISI_BL2_EFUSE_SHMEM_SIZE 0x1000
#define HISI_BL2_EFUSE_SHMEM_ADDR (HISI_BL2_DDR_SHMEM_ADDR - HISI_BL2_EFUSE_SHMEM_SIZE)
#define HISI_BL2_SHMEM_RESERVE_SIZE (0x10000 - HISI_BL2_DDR_SHMEM_SIZE - HISI_BL2_EFUSE_SHMEM_SIZE)
#define HISI_BL2_SHMEM_RESERVE_ADDR (HISI_BL2_EFUSE_SHMEM_ADDR - HISI_BL2_SHMEM_RESERVE_SIZE)
#define ATF_BL2_SECRAM_END (HISI_BL2_SHMEM_RESERVE_ADDR)
#define HISI_BL2_CC_PAL_SIZE 0x100000
#define HISI_BL2_CC_PAL_ADDR (ATF_BL2_SECRAM_END - HISI_BL2_CC_PAL_SIZE)
#endif
