#ifndef __MSPC_MEM_LAYOUT_H__
#define __MSPC_MEM_LAYOUT_H__ 
#include <soc_acpu_baseaddr_interface.h>
#include <bl31_platform_memory_def.h>
#define MSPC_RPMB_REGION0_SIZE 0x300000
#define MSPC_RPMB_REGION1_SIZE 0x200000
#define MSPC_RPMB_REGION2_SIZE 0x400000
#define MSPC_SECRPMB_ADDR 0x0
#define MSPC_SECRPMB_SIZE 0x80000
#define MSPC_RPMB_REGION0_USED_SIZE MSPC_SECRPMB_SIZE
#define MSPC_RPMB_START_ADDR 0x0
#define MSPC_RPMB_TOTAL_SIZE MSPC_RPMB_REGION1_SIZE
#define MSPC_RPMB_IMAGE_ADDR MSPC_RPMB_START_ADDR
#define MSPC_RPMB_IMAGE_SIZE 0x00072000
#define MSPC_RPMB_RESVD_ADDR (MSPC_RPMB_IMAGE_ADDR + MSPC_RPMB_IMAGE_SIZE)
#define MSPC_RPMB_RESVD_SIZE 0x0000E000
#define MSPC_RPMB_DCS_ADDR (MSPC_RPMB_RESVD_ADDR + MSPC_RPMB_RESVD_SIZE)
#define MSPC_RPMB_DCS_SIZE (404 * 1024)
#define MSPC_RPMB_SYSTEM_ADDR (MSPC_RPMB_DCS_ADDR + MSPC_RPMB_DCS_SIZE)
#define MSPC_RPMB_SYSTEM_SIZE (64 * 1024)
#define MSPC_RPMB_NVM_ADDR (MSPC_RPMB_SYSTEM_ADDR + MSPC_RPMB_SYSTEM_SIZE)
#define MSPC_RPMB_NVM_SIZE (1068 * 1024)
#define MSPC_RPMB_SYS_DATA_MAX_ADDR \
 (MSPC_RPMB_SYSTEM_ADDR + MSPC_RPMB_SYSTEM_SIZE)
#define MSPC_RPMB_BLOCK_SIZE 256
#define MSPC_RPMB_AUTHSWITCH_ADDR \
 (MSPC_RPMB_SYS_DATA_MAX_ADDR - MSPC_RPMB_AUTHSWITCH_SIZE)
#define MSPC_RPMB_AUTHSWITCH_SIZE MSPC_RPMB_BLOCK_SIZE
#define MSPC_RPMB_SECFLASH_FLAG_ADDR \
 (MSPC_RPMB_AUTHSWITCH_ADDR - MSPC_RPMB_SECFLASH_FLAG_SIZE)
#define MSPC_RPMB_SECFLASH_FLAG_SIZE MSPC_RPMB_BLOCK_SIZE
#define MSPC_RPMB_SECFLASH_INFO_OFFSET 0
#define MSPC_RPMB_SECFLASH_AVAILABLE_OFFSET 1
#define MSPC_FAKE_RPMB_REGION1_OFFSET 0
#define MSPC_FAKE_RPMB_REGION2_OFFSET (MSPC_FAKE_RPMB_REGION1_OFFSET + MSPC_RPMB_REGION1_SIZE)
#define MSPC_FAKE_RPMB_REGION0_OFFSET (MSPC_FAKE_RPMB_REGION2_OFFSET + MSPC_RPMB_REGION2_SIZE)
#define MSPC_FAKE_RPMB_SIZE (MSPC_FAKE_RPMB_REGION0_OFFSET + MSPC_SECRPMB_SIZE)
#define MSPC_DDR_START_ADDR HISI_BL31_HISEE_ADDR
#define MSPC_DDR_TOTAL_SIZE HISI_BL31_HISEE_SIZE
#define MSPC_DDR_RESVD_ADDR MSPC_DDR_START_ADDR
#define MSPC_DDR_RESVD_SIZE 0x0000E000
#define MSPC_DDR_IMAGE_ADDR (MSPC_DDR_RESVD_ADDR + MSPC_DDR_RESVD_SIZE)
#define MSPC_DDR_IMAGE_SIZE MSPC_RPMB_IMAGE_SIZE
#define MSPC_DDR_DCS_ADDR (MSPC_DDR_IMAGE_ADDR + MSPC_DDR_IMAGE_SIZE)
#define MSPC_DDR_DCS_SIZE MSPC_RPMB_DCS_SIZE
#define MSPC_DDR_SYSTEM_ADDR (MSPC_DDR_DCS_ADDR + MSPC_DDR_DCS_SIZE)
#define MSPC_DDR_SYSTEM_SIZE MSPC_RPMB_SYSTEM_SIZE
#define MSPC_DDR_NVM_ADDR (MSPC_DDR_SYSTEM_ADDR + MSPC_DDR_SYSTEM_SIZE)
#define MSPC_DDR_NVM_SIZE MSPC_RPMB_NVM_SIZE
#define MSPC_DDR_FLASH_COS_ADDR (MSPC_DDR_START_ADDR + MSPC_RPMB_TOTAL_SIZE)
#define MSPC_DDR_FLASH_COS_SIZE 0x80000
#define MSPC_DDR_DATA_ADDR (MSPC_DDR_FLASH_COS_ADDR + MSPC_DDR_FLASH_COS_SIZE)
#define MSPC_DDR_DATA_SIZE 0x27D000
#define MSPC_DDR_RESERVED_ADDR (MSPC_DDR_DATA_ADDR + MSPC_DDR_DATA_SIZE)
#define MSPC_DDR_RESERVED_SIZE 0xF00
#define MSPC_DDR_FLAG_ADDR (MSPC_DDR_START_ADDR + \
 MSPC_DDR_TOTAL_SIZE - MSPC_DDR_FLAG_TOTAL_SIZE)
#define MSPC_DDR_FLAG_OFFSET (MSPC_DDR_LAST_PAGE_SIZE - \
 MSPC_DDR_FLAG_TOTAL_SIZE)
#define MSPC_DDR_FLAG_TOTAL_SIZE 0x100
#define MSPC_DDR_MNTN_MAGIC_ADDR MSPC_DDR_FLAG_ADDR
#define MSPC_DDR_MNTN_MAGIC_OFFSET MSPC_DDR_FLAG_OFFSET
#define MSPC_DDR_MNTN_MAGIC_SIZE 0x4
#define MSPC_DDR_UPGRADE_LIMT_ADDR (MSPC_DDR_MNTN_MAGIC_ADDR + \
 MSPC_DDR_MNTN_MAGIC_SIZE)
#define MSPC_DDR_UPGRADE_LIMT_OFFSET (MSPC_DDR_MNTN_MAGIC_OFFSET + \
 MSPC_DDR_MNTN_MAGIC_SIZE)
#define MSPC_DDR_UPGRADE_LIMT_SIZE 0x4
#define MSPC_TEE_VOTE_STATUS_ADDR (MSPC_DDR_UPGRADE_LIMT_ADDR + \
 MSPC_DDR_UPGRADE_LIMT_SIZE)
#define MSPC_TEE_VOTE_STATUS_OFFSET (MSPC_DDR_UPGRADE_LIMT_OFFSET + \
 MSPC_DDR_UPGRADE_LIMT_SIZE)
#define MSPC_TEE_VOTE_STATUS_SIZE 0x8
#define MSPC_SECFLASH_INFO_ADDR (MSPC_TEE_VOTE_STATUS_ADDR + \
 MSPC_TEE_VOTE_STATUS_SIZE)
#define MSPC_SECFLASH_INFO_OFFSET (MSPC_TEE_VOTE_STATUS_OFFSET + \
 MSPC_TEE_VOTE_STATUS_SIZE)
#define MSPC_SECFLASH_INFO_SIZE 0x4
#define MSPC_UPGRADE_FLAG_ADDR (MSPC_SECFLASH_INFO_ADDR + \
 MSPC_SECFLASH_INFO_SIZE)
#define MSPC_UPGRADE_FLAG_OFFSET (MSPC_SECFLASH_INFO_OFFSET + \
 MSPC_SECFLASH_INFO_SIZE)
#define MSPC_UPGRADE_FLAG_SIZE 0x4
#define MSPC_SECFLASH_STATUS_ADDR (MSPC_UPGRADE_FLAG_ADDR + \
 MSPC_UPGRADE_FLAG_SIZE)
#define MSPC_SECFLASH_STATUS_OFFSET (MSPC_UPGRADE_FLAG_OFFSET + \
 MSPC_UPGRADE_FLAG_SIZE)
#define MSPC_SECFLASH_STATUS_SIZE 0x4
#define MSPC_RECOVERY_STATUS_ADDR (MSPC_SECFLASH_STATUS_ADDR + \
 MSPC_SECFLASH_STATUS_SIZE)
#define MSPC_RECOVERY_STATUS_OFFSET (MSPC_SECFLASH_STATUS_OFFSET + \
 MSPC_SECFLASH_STATUS_SIZE)
#define MSPC_RECOVERY_STATUS_SIZE 0x4
#define MSPC_WRITELOCK_STATUS_ADDR (MSPC_RECOVERY_STATUS_ADDR + \
 MSPC_RECOVERY_STATUS_SIZE)
#define MSPC_WRITELOCK_STATUS_OFFSET (MSPC_RECOVERY_STATUS_OFFSET + \
 MSPC_RECOVERY_STATUS_SIZE)
#define MSPC_WRITELOCK_STATUS_SIZE 0x4
#define MSPC_ATF_VOTE_STATUS_ADDR (MSPC_WRITELOCK_STATUS_ADDR + \
 MSPC_WRITELOCK_STATUS_SIZE)
#define MSPC_ATF_VOTE_STATUS_OFFSET (MSPC_WRITELOCK_STATUS_OFFSET + \
 MSPC_WRITELOCK_STATUS_SIZE)
#define MSPC_ATF_VOTE_STATUS_SIZE 0x4
#define MSPC_LPMCU_VOTE_STATUS_ADDR (MSPC_ATF_VOTE_STATUS_ADDR + \
 MSPC_ATF_VOTE_STATUS_SIZE)
#define MSPC_LPMCU_VOTE_STATUS_OFFSET (MSPC_ATF_VOTE_STATUS_OFFSET + \
 MSPC_ATF_VOTE_STATUS_SIZE)
#define MSPC_LPMCU_VOTE_STATUS_SIZE 0x4
#if ((MSPC_DDR_MNTN_MAGIC_SIZE + MSPC_DDR_UPGRADE_LIMT_SIZE + \
 MSPC_TEE_VOTE_STATUS_SIZE + MSPC_SECFLASH_INFO_SIZE + \
 MSPC_UPGRADE_FLAG_SIZE + MSPC_SECFLASH_STATUS_SIZE + \
 MSPC_RECOVERY_STATUS_SIZE + MSPC_WRITELOCK_STATUS_SIZE + \
 MSPC_ATF_VOTE_STATUS_SIZE + MSPC_LPMCU_VOTE_STATUS_SIZE) > \
 MSPC_DDR_FLAG_TOTAL_SIZE)
#error "mspc ddr flag region size overflow!!!!"
#endif
#define MSPC_DDR_LAST_PAGE_ADDR (MSPC_DDR_START_ADDR + \
 MSPC_DDR_TOTAL_SIZE - MSPC_DDR_LAST_PAGE_SIZE)
#define MSPC_DDR_LAST_PAGE_SIZE (4 * 1024)
#define MSPC_MBXRAM_PHYMEM_ADDR (SOC_ACPU_HISEE_MAILBOX_BASE_ADDR)
#define MSPC_MBXRAM_PHYMEM_SIZE 0x4000
#define MSPC_MBXRAM_IPC_PHYMEM_ADDR (MSPC_MBXRAM_PHYMEM_ADDR)
#define MSPC_MBXRAM_IPC_PHYMEM_SIZE 0x3800
#define MSPC_MBXRAM_MNTN_BUFFER_PHYMEM_ADDR \
 (MSPC_MBXRAM_IPC_PHYMEM_ADDR + MSPC_MBXRAM_IPC_PHYMEM_SIZE)
#define MSPC_MBXRAM_MNTN_BUFFER_PHYMEM_SIZE 0x7B0
#define MSPC_MBXRAM_PROCESS_MTRACE_PHYMEM_ADDR \
 (MSPC_MBXRAM_MNTN_BUFFER_PHYMEM_ADDR + \
 MSPC_MBXRAM_MNTN_BUFFER_PHYMEM_SIZE)
#define MSPC_MBXRAM_PROCESS_MTRACE_PHYMEM_SIZE 4
#define MSPC_MBXRAM_COSID_PHYMEM_ADDR \
 (MSPC_MBXRAM_PROCESS_MTRACE_PHYMEM_ADDR + \
 MSPC_MBXRAM_PROCESS_MTRACE_PHYMEM_SIZE)
#define MSPC_MBXRAM_COSID_PHYMEM_SIZE 4
#define MSPC_MBXRAM_OTP_PGM_STATUS_PHYMEM_ADDR \
 (MSPC_MBXRAM_COSID_PHYMEM_ADDR)
#define MSPC_MBXRAM_OTP_PGM_STATUS_PHYMEM_SIZE 4
#define MSPC_MBXRAM_IS_DONE_FLAG_PHYMEM_ADDR \
 (MSPC_MBXRAM_COSID_PHYMEM_ADDR)
#define MSPC_MBXRAM_IS_DONE_FLAG_PHYMEM_SIZE 4
#define MSPC_MBXRAM_RPMB_DEVICE_INFO_PHYMEM_ADDR \
 (MSPC_MBXRAM_COSID_PHYMEM_ADDR + MSPC_MBXRAM_COSID_PHYMEM_SIZE)
#define MSPC_MBXRAM_RPMB_DEVICE_INFO_PHYMEM_SIZE 4
#define MSPC_MBXRAM_SECFLASH_DTS_INFO_PHYMEM_ADDR \
 (MSPC_MBXRAM_RPMB_DEVICE_INFO_PHYMEM_ADDR)
#define MSPC_MBXRAM_SECFLASH_DTS_INFO_PHYMEM_SIZE 4
#define MSPC_MBXRAM_SYSRST_SAVED_FLAG_PHYMEM_ADDR \
 (MSPC_MBXRAM_RPMB_DEVICE_INFO_PHYMEM_ADDR + \
 MSPC_MBXRAM_RPMB_DEVICE_INFO_PHYMEM_SIZE)
#define MSPC_MBXRAM_SYSRST_SAVED_FLAG_PHYMEM_SIZE 4
#define MSPC_MBXRAM_SYSRST_STATE_PHYMEM_ADDR \
 (MSPC_MBXRAM_SYSRST_SAVED_FLAG_PHYMEM_ADDR + \
 MSPC_MBXRAM_SYSRST_SAVED_FLAG_PHYMEM_SIZE)
#define MSPC_MBXRAM_SYSRST_STATE_PHYMEM_SIZE 4
#define MSPC_MBXRAM_DEBUG_ROM_READY_PHYMEM_ADDR \
 (MSPC_MBXRAM_SYSRST_STATE_PHYMEM_ADDR)
#define MSPC_MBXRAM_DEBUG_ROM_READY_PHYMEM_SIZE 4
#define MSPC_MBXRAM_SC_ALARM_STATE_PHYMEM_ADDR \
 (MSPC_MBXRAM_SYSRST_STATE_PHYMEM_ADDR + \
 MSPC_MBXRAM_SYSRST_STATE_PHYMEM_SIZE)
#define MSPC_MBXRAM_SC_ALARM_STATE_PHYMEM_SIZE 4
#define MSPC_MBXRAM_MB_SOFT_FAULT_ID_PHYMEM_ADDR \
 (MSPC_MBXRAM_SC_ALARM_STATE_PHYMEM_ADDR + \
 MSPC_MBXRAM_SC_ALARM_STATE_PHYMEM_SIZE)
#define MSPC_MBXRAM_MB_SOFT_FAULT_ID_PHYMEM_SIZE 4
#define MSPC_MBXRAM_MB_SOFT_FAULT_VALUE_PHYMEM_ADDR \
 (MSPC_MBXRAM_MB_SOFT_FAULT_ID_PHYMEM_ADDR + \
 MSPC_MBXRAM_MB_SOFT_FAULT_ID_PHYMEM_SIZE)
#define MSPC_MBXRAM_MB_SOFT_FAULT_VALUE_PHYMEM_SIZE 4
#define MSPC_MBXRAM_SYS_CLOCK_CFG_PHYMEM_ADDR \
 (MSPC_MBXRAM_MB_SOFT_FAULT_VALUE_PHYMEM_ADDR +\
 MSPC_MBXRAM_MB_SOFT_FAULT_VALUE_PHYMEM_SIZE)
#define MSPC_MBXRAM_SYS_CLOCK_CFG_PHYMEM_SIZE 4
#define MSPC_MBXRAM_DEBUG_ROM_LOOP_PHYMEM_ADDR \
 (MSPC_MBXRAM_SYS_CLOCK_CFG_PHYMEM_ADDR)
#define MSPC_MBXRAM_DEBUG_ROM_LOOP_PHYMEM_SIZE 4
#define MSPC_MBXRAM_BOOT_MISC_FLAG_PHYMEM_ADDR \
 (MSPC_MBXRAM_SYS_CLOCK_CFG_PHYMEM_ADDR + \
 MSPC_MBXRAM_SYS_CLOCK_CFG_PHYMEM_SIZE)
#define MSPC_MBXRAM_BOOT_MISC_FLAG_PHYMEM_SIZE 4
#define MSPC_MBXRAM_PROCESS_MAGIC_PHYMEM_ADDR \
 (MSPC_MBXRAM_BOOT_MISC_FLAG_PHYMEM_ADDR + \
 MSPC_MBXRAM_BOOT_MISC_FLAG_PHYMEM_SIZE)
#define MSPC_MBXRAM_PROCESS_MAGIC_PHYMEM_SIZE 4
#define MSPC_MBXRAM_SMX_PROCESS_PHYMEM_ADDR \
 (MSPC_MBXRAM_PROCESS_MAGIC_PHYMEM_ADDR)
#define MSPC_MBXRAM_SMX_PROCESS_PHYMEM_SIZE 4
#define MSPC_MBXRAM_PROCESS_FLAG_PHYMEM_ADDR \
 (MSPC_MBXRAM_PROCESS_MAGIC_PHYMEM_ADDR + \
 MSPC_MBXRAM_PROCESS_MAGIC_PHYMEM_SIZE)
#define MSPC_MBXRAM_PROCESS_FLAG_PHYMEM_SIZE 4
#define MSPC_MBXRAM_SECUREDEBUG_FLAG_PHYMEM_ADDR \
 (MSPC_MBXRAM_PROCESS_FLAG_PHYMEM_ADDR)
#define MSPC_MBXRAM_SECUREDEBUG_FLAG_PHYMEM_SIZE 4
#define MSPC_MBXRAM_SHUTDOWN_SWIPE_FLAG_PHYMEM_ADDR \
 (MSPC_MBXRAM_PROCESS_FLAG_PHYMEM_ADDR)
#define MSPC_MBXRAM_SHUTDOWN_SWIPE_FLAG_PHYMEM_SIZE 4
#define MSPC_MBXRAM_TABLE_PHYMEM_ADDR \
 (MSPC_MBXRAM_PROCESS_FLAG_PHYMEM_ADDR + \
 MSPC_MBXRAM_PROCESS_FLAG_PHYMEM_SIZE)
#define MSPC_MBXRAM_TABLE_PHYMEM_SIZE 32
#if ((MSPC_MBXRAM_TABLE_PHYMEM_ADDR + MSPC_MBXRAM_TABLE_PHYMEM_SIZE) > \
 (MSPC_MBXRAM_PHYMEM_ADDR + MSPC_MBXRAM_PHYMEM_SIZE))
#error "mspc mailbox ram beyond the boundary!!!"
#endif
#endif
