obj-$(CONFIG_SCHARGER_V600) += hisi_scharger_v600.o
obj-$(CONFIG_SCHARGER_V600) += hisi_scharger_v600_base.o
obj-$(CONFIG_SCHARGER_V600) += hisi_scharger_v600_direct_charge.o
obj-$(CONFIG_SCHARGER_V600) += hisi_scharger_v600_irq.o