obj-$(CONFIG_ADSP_DTS) += dts/
obj-$(CONFIG_ADSP_DIRECT_CHARGER) += direct_charger/
obj-$(CONFIG_ADSP_BATTERY) += battery/
obj-$(CONFIG_ADSP_CHARGER) += charger/
obj-$(CONFIG_ADSP_UI_EVENT) += event/
obj-$(CONFIG_ADSP_USB) += usb/
