	.text
	.file	"mas_bkops_sysfs.c"
	.globl	mas_bkops_add_debugfs   // -- Begin function mas_bkops_add_debugfs
	.p2align	2
	.type	mas_bkops_add_debugfs,@function
mas_bkops_add_debugfs:                  // @mas_bkops_add_debugfs
// %bb.0:
	mov	w0, wzr
	ret
.Lfunc_end0:
	.size	mas_bkops_add_debugfs, .Lfunc_end0-mas_bkops_add_debugfs
                                        // -- End function

	.ident	"Android (27847 based on r353983c) clang version 9.0.3 (https://android.googlesource.com/toolchain/clang dbdb7a2acf33dc76cd6f506c323253b8d892ae05) (https://android.googlesource.com/toolchain/llvm f32df87f6769ededcd9e2a6c3c4c45c1baf361c2) (based on LLVM 9.0.3svn)"
	.section	".note.GNU-stack","",@progbits
