obj-$(CONFIG_LCD_KIT_SPRD) 	+= tps65132.o
obj-$(CONFIG_LCD_KIT_SPRD)	+= rt4801h.o
obj-$(CONFIG_LCD_KIT_SPRD) 	+= sm5109.o

EXTRA_CFLAGS +=-Idrivers/staging/android \
		-Idrivers/atfdriver \
		-Idrivers/devkit/lcdkit/lcdkit3.0 \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/common/include \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/sprd/include \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/sprd/adapt
