obj-$(CONFIG_RPMB_AGENT) += agent_rpmb/
obj-$(CONFIG_TZDRIVER) += auth/
obj-$(CONFIG_TZDRIVER) += core/
obj-$(CONFIG_TZDRIVER) += ion/
obj-$(CONFIG_TZDRIVER) += tlogger/
obj-$(CONFIG_TEE_TUI) += tui/
obj-$(CONFIG_TEE_ANTIROOT_CLIENT) += ca_antiroot/
#obj-$(CONFIG_TZDRIVER_MODULE) += ko_adapt.o
