obj-$(CONFIG_HUAWEI_CHARGER) += charger_ic/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_charge_ic/
obj-$(CONFIG_LOADSWITCH) += load_switch/
obj-$(CONFIG_SWITCHCAP) += switch_capacitor/
obj-$(CONFIG_FUEL_GAUGE) += fuel_gauge/