obj-y      += qcom_usb_temp.o
obj-y      += huawei_charger_common.o
obj-$(CONFIG_FCP_CHARGER) += fcp_charger.o
obj-$(CONFIG_HIHONOR_OEM_GLINK) += hihonor_charger_glink.o
obj-$(CONFIG_HIHONOR_OEM_GLINK) += hihonor_adsp_log.o
