obj-$(CONFIG_LCD_KIT) += ktd3133.o
obj-$(CONFIG_LCD_KIT) += lm3697.o
obj-$(CONFIG_LCD_KIT) += sgm37603a.o
obj-$(CONFIG_LCD_KIT) += lm36923.o
obj-$(CONFIG_LCD_KIT) += ktz8864.o
obj-$(CONFIG_LCD_KIT) += lm36274.o
obj-$(CONFIG_LCD_KIT) += rt4831.o
obj-$(CONFIG_LCD_KIT) += nt50356.o
obj-$(CONFIG_LCD_KIT) += aw99703.o
obj-$(CONFIG_LCD_KIT) += sm5350.o
obj-$(CONFIG_LCD_KIT) += ktd3136.o
obj-$(CONFIG_LCD_KIT) += lp8556.o
obj-$(CONFIG_LCD_KIT) += rt8555.o
obj-$(CONFIG_LCD_KIT) += lcd_bl_linear_exponential_table.o

