# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_HUAWEI_CHARGER) += charger/
obj-$(CONFIG_HONOR_ADC) += huawei_adc/
obj-$(CONFIG_HUAWEI_DUBAI) += dubai/
obj-$(CONFIG_KSTATE) += hw_kstate/
