#obj-$(CONFIG_HUAWEI_HALL_SENSORS)			+= hallsensor/
#obj-$(CONFIG_HUAWEI_LP_SENSORS)				+= lpsensor/

obj-$(CONFIG_HUAWEI_PS_SENSOR)				+= pssensor/
#obj-$(CONFIG_SENSOR_DEVELOP_TEST)			+= develop_test.o
#obj-$(CONFIG_HUAWEI_SENSOR_INFO)			+= hw_sensor_info.o
#obj-$(CONFIG_HUAWEI_SAR_SENSOR)				+= sarsensor/
obj-$(CONFIG_HUAWEI_PS_SENSOR)               += sensors_class.o

obj-y                                        += fingersense.o
obj-$(CONFIG_HUAWEI_COLOR_SENSOR)            += colorsensor/
obj-$(CONFIG_HONOR_SENSOR_EVENT)             += sensorevent/
obj-y                                        += sensors_dmd.o
