obj-$(CONFIG_WIRELESS_CHARGER) += wireless_power_supply.o

obj-$(CONFIG_WIRELESS_CHARGER) += wireless_test/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_rx/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx/
