obj-$(CONFIG_LCD_KIT_SPRD) += backlight_linear_to_exp.o
obj-$(CONFIG_LCD_KIT_SPRD) += ktd3133.o
obj-$(CONFIG_LCD_KIT_SPRD) += lm3697.o
obj-$(CONFIG_LCD_KIT_SPRD) += sgm37603a.o
obj-$(CONFIG_LCD_KIT_SPRD) += lm36923.o
obj-$(CONFIG_LCD_KIT_SPRD) += ktz8864.o
obj-$(CONFIG_LCD_KIT_SPRD) += lm36274.o
obj-$(CONFIG_LCD_KIT_SPRD) += rt4831.o
obj-$(CONFIG_LCD_KIT_SPRD) += nt50356.o
obj-$(CONFIG_LCD_KIT_SPRD) += aw99703.o
obj-$(CONFIG_LCD_KIT_SPRD) += sm5350.o
obj-$(CONFIG_LCD_KIT_SPRD) += ktd3136.o
obj-$(CONFIG_LCD_KIT_SPRD) += lp8556.o
obj-$(CONFIG_LCD_KIT_SPRD) += rt8555.o

EXTRA_CFLAGS +=-Idrivers/staging/android \
		-Idrivers/atfdriver \
		-Idrivers/devkit/lcdkit/lcdkit3.0 \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/common/include \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/sprd/include \
		-Idrivers/devkit/lcdkit/lcdkit3.0/kernel/sprd/adapt
