obj-$(CONFIG_HN_HAPTICS_WRAPPER) += hn_haptics_wrapper.o
obj-$(CONFIG_HN_HAPTICS_VIBRATOR) += aw01624/
obj-$(CONFIG_HN_HAPTICS_VIBRATOR) += drv2624/
obj-$(CONFIG_HONOR_VIBRATOR_LDO) += honor_vibrator_ldo.o
