obj-$(CONFIG_LCD_KIT) += lcd_kit_disp.o
obj-$(CONFIG_LCD_KIT) += lcd_kit_effect.o
obj-$(CONFIG_LCD_KIT) += lcd_kit_power.o
obj-$(CONFIG_LCD_KIT) += lcd_kit_utils.o
obj-$(CONFIG_LCD_KIT) += lcd_kit_panel.o

