#
# Copyright (c) 2021-2021 Honor Technologies Co., Ltd. All Rights Reserved.
# Description: gc5035 customsized driver,
#    otp read function is samed as it's kernel driver.
# Create: 2021-01-29
#

obj-y += gc5035_m200_kob.o