obj-$(CONFIG_LCD_KIT) += lcd_kit_common.o
obj-$(CONFIG_LCD_KIT) += lcd_kit_parse.o
obj-$(CONFIG_LCD_KIT) += lcd_kit_bl.o
obj-$(CONFIG_LCD_KIT) += lcd_kit_bias.o
obj-$(CONFIG_LCD_KIT) += bias_bl_common.o
obj-$(CONFIG_LCD_KIT) += bias_ic_common.o

